# Generated by Django 4.1.3 on 2023-01-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messagesdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.CharField(blank=True, max_length=20, null=True)),
                ('Subject', models.CharField(blank=True, max_length=20, null=True)),
                ('Textarea', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
