# Generated by Django 4.1.3 on 2023-01-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesdb',
            name='Textarea',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
