# Generated by Django 4.1.3 on 2023-01-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_messagesdb_textarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='emailsubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emailsub', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
