# Generated by Django 4.1.3 on 2023-01-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bikedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model', models.CharField(blank=True, max_length=20, null=True)),
                ('Company', models.CharField(blank=True, max_length=20, null=True)),
                ('Year', models.IntegerField(blank=True, max_length=20, null=True)),
                ('Color', models.CharField(blank=True, max_length=200, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('Category', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
