# Generated by Django 4.1.3 on 2023-01-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikedata',
            old_name='Color',
            new_name='Description',
        ),
        migrations.RemoveField(
            model_name='bikedata',
            name='Year',
        ),
        migrations.AddField(
            model_name='bikedata',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
