# Generated by Django 4.1.3 on 2023-01-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0002_rename_color_bikedata_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikedata',
            name='Description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
