# Generated by Django 4.1.3 on 2023-01-03 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0003_alter_bikedata_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikedata',
            old_name='Model',
            new_name='Bikename',
        ),
    ]
