# Generated by Django 4.1.3 on 2023-01-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0004_rename_model_bikedata_bikename'),
    ]

    operations = [
        migrations.CreateModel(
            name='bikecategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(blank=True, max_length=20, null=True)),
                ('CatDescription', models.CharField(blank=True, max_length=400, null=True)),
                ('CatImage', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
    ]
