# Generated by Django 4.1.3 on 2023-01-04 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0005_bikecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikedata',
            name='Category',
        ),
    ]
