# Generated by Django 4.1.3 on 2023-01-05 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0007_admindb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikecategory',
            name='CatImage',
        ),
    ]
