# Generated by Django 4.1.3 on 2023-01-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0009_bikedata_pcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikecategory',
            name='CatImage',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
